Taha branch (#115)
* mark core & tools as sub_packages

* update get_frequency_of_characters function

* suppress __pycache__

* add frequency_sura_level()

* add frequency_quran_level المعج الترددى كهيكل بياناتٍ برمجى

* hamza_above issue

* add hamza_above to the alphabet

* add xml prettify

* add get_unique_words()

* add get_words()

* add quran_words_frequences_data() المعجم الترددى xml

* Using example

* add filteration issues

* importing the corpus issue;

Making the path is relative to the location of the module,
instead of being relative to the run location.

* comforming to the new system desgin

* adding hamza_above

* preparing PyQuran for usage

* remove uu0655 hamza below from the alphabet

* Remove pyarabic dependancy

```
In [1]: import quran
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py",
line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-8ce127e44449>", line 1, in <module>
    import quran

  File "/Users/taha/PyQuran/tools/quran.py", line 4, in <module>
    from pyarabic.araby import strip_tashkeel

  File "/usr/local/lib/python3.6/site-packages/pyarabic/araby.py", line 219
    HARAKAT_PATTERN = re.compile(ur"[" + u"".join(HARAKAT) + u"]", re.UNICODE)
                                     ^
SyntaxError: invalid syntax
```

* add basmalah option

* ignore python notebooks

* removing tashkeel of small letters while removing them

* add retrieve_qruan_as_one_string

* test

* remove test

* adding docs

* chning to the new origin

* generate docs script

* add site configurations

* add autogen templates

* add docs files

* add auto_gen_docs.py!

* nothing

* fixing doc issue; datatype :

* fixing doc issue

* cleaning !

* add the website

* adding quran.py docs

* fixing documentation issue

* author -temp

* some updates

* add examples to function docs

* changing to new names

* changing docs format (parsing)

* `Example:` format --autogeneration

* count_shape docs

* remove useless functions

* !

* excluding letters () docs

* remove useless fns

* strip... docs

* docs

* finishing arabic tools docs

* analysis part, docs

* authors page

* syncing README.md with the website index

* syncing README.md with the website index

* syncing README with the website index

* syncing README with the website index

* Filtering update

* test

* test

* syncing contribution.md

* syncying

* syncying

* syncing